#!/bin/bash
# system tools
pip install \
    httpie \
    supervisor \
    sphinx \
    lice \
    pydot \
    ffind \
    vanity \
    pyparsing==1.5.7 \
    ngxtop \
    percol \
    speedtest-cli \
    pgcli \
    eg \
    whatever \
    pythonpy \
    glances \
    ohmu \
    pinggraph \
    magic-wormhole \

pip3 install \
    fades

# neovim dependences
pip install neovim pep8 flake8 pyflakes pylint isort
pip3 install neovim pep8 flake8 pyflakes pylint isort
