#!/bin/bash

# create user invitado
echo " >>>> INVITADO USER"
sudo adduser invitado

# create postgres user
echo " >>>> POSTGRES USER"
sudo -u postgres createuser sofi -s -P
# default postgres database for my user
createdb sofi

# add my ssh key
echo " >>>> SSH KEY"
ssh-add /home/sofi/.ssh/sofide

# add local bin path to fish
fish -c "set -U fish_user_paths /home/sofi/.local/bin $fish_user_paths"
